#!/bin/bash -ue

function replace_with_symlink () {
    rm -f ~/$1 && ln -s $(pwd)/$1 ~/$1
}

echo "Installing files in user home directory.."
replace_with_symlink .bashrc
replace_with_symlink .vimrc
replace_with_symlink .tmux.conf

mkdir -p ~/.local/bin
replace_with_symlink .local/bin/tat

mkdir -p ~/.config/kitty
replace_with_symlink .config/kitty/kitty.conf

mkdir -p ~/.vim
replace_with_symlink .vim/coc-settings.json

cp -r ./.vim/colors ~/.vim/

echo "Installing KDE settings..."
./scripts/user-init/kde-settings

echo "Installing Vim plugins.."
cp -r ./.vim/plugin ~/.vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qa
vim +PlugUpdate +qa
vim "+CocInstall $(cat ./manifests/vim-coc-exts | tr "\n" " " | head --bytes -1)"

