#!/bin/bash -ue

plasma-apply-colorscheme SweetAmbarBlue
plasma-apply-desktoptheme Sweet-Ambar-Blue

#
# The following settings require a reboot to be functional.
#

# Write configurations for kitty.
kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group kitty.desktop --key _k_friendly_name "kitty"
kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group kitty.desktop --key _launch "Ctrl+Alt+T,none,kitty"
kwriteconfig5 --file ~/.config/kdeglobals --group General --key TerminalApplication "kitty"
kwriteconfig5 --file ~/.config/kdeglobals --group General --key TerminalService "kitty.deskop"

# Write keyboard configurations.
kwriteconfig5 --file ~/.config/kcminputrc --group Keyboard --key RepeatDelay 200
kwriteconfig5 --file ~/.config/kcminputrc --group Keyboard --key RepeatRate 60
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key LayoutList us,ara
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key DisplayList ,
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key VariantList ,
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key Options grp:alt_shift_toggle,caps:ctrl_modifier
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key ResetOldOptions true
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key Use true

# Write timezone settings
kwriteconfig5 --file ~/.config/ktimezonedrc --group TimeZones --key LocalZone Europe/Amsterdam
kwriteconfig5 --file ~/.config/ktimezonedrc --group TimeZones --key ZoneinfoDir /usr/share/zoneinfo
kwriteconfig5 --file ~/.config/ktimezonedrc --group TimeZones --key Zonetab /usr/share/zoneinfo/zone.tab

# Change Application Launcher icon.
mkdir -p ~/.local/share/icons
cp ./assets/archlinux-icon.svg ~/.local/share/icons
kwriteconfig5 --file ~/.config/plasma-org.kde.plasma.desktop-appletsrc \
    --group Containments --group 2 --group Applets --group 3 \
    --group Configuration --group General \
    --key icon $(echo ~/.local/share/icons/archlinux-icon.svg)

kwriteconfig5 --file ~/.config/kwinrc --group org.kde.kdecoration2 --key ButtonsOnLeft M

# Write configurations for Tab layout.
kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key LayoutName thumbnail_grid

# Write configuration for Night mode.
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key Active true
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key LatitudeAuto 30.0778
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key LongtitudeAuto 31.2852
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key Mode Contrast
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key NightTemperature 4000

# Dim screen on Adminstrator mode
kwriteconfig5 --file ~/.config/kwinrc --group Plugins --key kwin4_effect_dimscreenEnabled true

# Set transparency for application menus.
kwriteconfig5 --file ~/.config/breezerc --group Style --key MenuOpacity 65

kwriteconfig5 --file ~/.config/ksplashrc --group KSplash --key Theme org.kde.oxygen
